/* Generated By:JavaCC: Do not edit this line. uml2svgConstants.java */
public interface uml2svgConstants {

  int EOF = 0;
  int DIAGRAM = 7;
  int DIAGRAM_TYPE = 8;
  int PACKAGE = 9;
  int COMMENT = 10;
  int RELATIONS = 11;
  int RELATION_TYPE = 12;
  int EQUAL = 16;
  int CLASS_TYPE = 17;
  int VISIBILITY = 18;
  int NUMBER = 19;
  int DIGIT = 20;
  int VARIABLE = 21;
  int DIAGRAM_NAME = 22;
  int STRING = 23;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"{\"",
    "\"}\"",
    "\"diagram\"",
    "\"uml\"",
    "\"package\"",
    "<COMMENT>",
    "\"relations\"",
    "<RELATION_TYPE>",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"=\"",
    "<CLASS_TYPE>",
    "<VISIBILITY>",
    "<NUMBER>",
    "<DIGIT>",
    "<VARIABLE>",
    "<DIAGRAM_NAME>",
    "<STRING>",
  };

}
